name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      ##setup the php 
      - name: Setup PHP
        id: setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: laravel/pint
      ##setup the phplint for check syntax
      - name: PHP check syntax
        uses: overtrue/phplint@8.1
        with:
          path: .
          options: --exclude=*.log

      ##run  check code sytle 
      - name: PHP style check(pint)
        run: pint --test
