name: Laravel CI Test
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      ##setup the php 
      - name: Setup PHP
        id: setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: laravel/pint
      ##setup the phplint for check syntax
      - name: PHP check syntax
        uses: overtrue/phplint@8.1
        with:
          path: .
          options: --exclude=*.log
       ##Fix the  style issues 
      - name: Fix PHP code style issues
        uses: aglipanci/laravel-pint-action@2.5

      ## Check PHP Style Again
      - name: PHP style check
        run: pint --test
      
