name: Laravel Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: laragigs
          MYSQL_USER: root
          MYSQL_PASSWORD: ""
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --host=127.0.0.1 --user=root"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
    - uses: actions/checkout@v4

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'

    - name: Copy .env
      run: cp .env.example .env

    - name: Install Dependencies
      run: composer install --no-progress --prefer-dist --no-interaction

    - name: Generate Application Key
      run: php artisan key:generate

    - name: Wait for MySQL to be ready
      run: |
        sudo apt-get install -y mysql-client
        until mysqladmin ping -h"127.0.0.1" --silent; do
          echo "Waiting for MySQL..."
          sleep 2
        done

    - name: Run Migrations
      run: php artisan migrate --force

    - name: Run Tests
      run: php artisan test
