name: Laravel CI Test
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Lint:
    runs-on: ubuntu-latest
    services:
     mysql:
      image: 
        mysql:8
      env:
         MYSQL_ALLOW_EMPTY_PASSWORD: yes
         MYSQL_DATABASE: laragigs
      ports:
      - 3306:3306
      options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      ##setup the php 
      - name: Setup PHP
        id: setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: laravel/pint
      ##setup the phplint for check syntax
      - name: PHP check syntax
        uses: overtrue/phplint@8.1
        with:
          path: .
          options: --exclude=*.log
          
      ##fix the style 
      
      - name: Fix PHP code style issues
        uses: aglipanci/laravel-pint-action@2.5
         
      ## Check PHP Style Again
      - name: PHP style check
        run: pint --test

      ##install composer dependencies
      - name: Install Composer dependencies
        env:
           COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}
        run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist   

      ##run tests
      - name: Run Tests
        env:
          DB_HOST: 127.0.0.1
          DB_PORT: ${{ job.services.mysql.ports['3306'] }}
          DB_USERNAME: root
          DB_PASSWORD: ''
          DB_DATABASE: laragigs
        run: vendor/bin/phpunit
      
