name: Laravel CI Test
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      ##setup the php 
      - name: Setup PHP
        id: setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: laravel/pint
      ##setup the phplint for check syntax
      - name: PHP check syntax
        uses: overtrue/phplint@8.1
        with:
          path: .
          options: --exclude=*.log
 
      ## Fix PHP Style Issues
      - name: Fix PHP Style Issues with Pint
        run: pint --dirty || true  

      ## Commit and Push Fixed Code
      - name: Commit and Push Fixes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Auto-fixed Laravel Pint style issues" || echo "No changes to commit"
          git push origin main || echo "No changes to push"

      ## Check PHP Style Again
      - name: PHP style check
        run: pint --test
      
